### ISSUE TITLE
feature: add Azure AD service principal support to create access policies

### ISSUE THREAD

**Issue by lampson** [kumarvna/terraform-azurerm-key-vault#7]
Will there be plans to extend this module to create access policies for service principals?

**Comment by kumarvna** [comment]
I have updated the code with the new release **(v2.2.0)**.  Please revert if any issues.

**Comment by lampson** [comment]
I tried v2.2.0 and it works great!  Thanks for the speedy update and the additional examples- I'll be sure to try those out shortly.  

BTW, the snippet of code I've provided above works fine and doesn't need a complete redesign of the module or any further changes for that matter.  I guess it's because a dynamic block for_each still takes a collection and iterates through to get the value so adding a key doesn't impact the value.  This add the flexibility I was looking for.  I'm no expert but it works for me.

**Comment by kumarvna** [comment]
Perfect! 👍
